#create a basic Node.js http server using the http module that runs on port 3000 and display a simple dynmaic website with 2 Page reqirements 1.homepage include html elemnts h1, paragraph tag and a button dynamic task display current date and time generated by Node.js
2.contact page include html elemnts H2CClient, form (email , name ,subit button) dynamic task show alert box
const http=require('http');
const server=http.createServer((req,res)=>{
    if(req.url==='/'){ 
        res.writeHead(200,{'Content-Type':'text/html'});
        const date=new Date();
        res.write('<h1>Welcome to the Homepage</h1>');
        res.write('<p>This is the homepage of our dynamic website.</p>');
        res.write('<button onclick="alert(\'Current Date and Time: ' + date + '\')">Show Date and Time</button>');
        res.end();
    } else if(req.url==='/contact'){
        res.writeHead(200,{'Content-Type':'text/html'});
        res.write('<h2>Contact Us</h2>');
        res.write('<form onsubmit="alert(\'Form submitted!\'); return false;">');
        res.write('<input type="text" name="name" placeholder="Your Name" required><br>');
        res.write('<input type="email" name="email" placeholder="Your Email" required><br>');
        res.write('<button type="submit">Submit</button>');
        res.write('</form>');
        res.end();
    
    }
});

server.listen(3000,()=>{
    console.log('Server is running on http://localhost:3000');
});